### ISSUE TITLE
Cannot compile StDict.pas 

### ISSUE THREAD

**Issue by rsgrimes** [TurboPack/SysTools#1]
I was able to install Orpheus and Abbrevia with no trouble at all to Delphi XE7, but cannot compile SysTools:

![image](https://cloud.githubusercontent.com/assets/3877641/6986482/a0438fc0-da0b-11e4-8a13-08c7b57e910b.png)

It is failing to find System.Hash.dcu, though it seems to be looking for it in the directory I put the SysTools in.

Any ideas?

**Comment by romankassebaum** [comment]
I'm currently busy, I will have a look at it at the end of the next week. If you need a solution earlier then please send me a pm.

**Comment by rsgrimes** [comment]
Thanks, Roman, that would be great!

**Comment by romankassebaum** [comment]
Write the following in StDict.pas

{code: Delphi}
implementation

uses
  Generics.Defaults;
{code}

and

{code: Delphi}
function HashStr(const S : string) : Integer;
begin
  if S <> '' then
    Result := BobJenkinsHash(S[1], Length(S) * SizeOf(S[1]), 0)
  else
    Result := 0;
end;
{code}

**Comment by rsgrimes** [comment]
That did it, thanks!

Best regards,
Bob


From:  Roman Kassebaum <notifications@github.com>
Reply-To:  TurboPack/SysTools
<reply+003b2b09baf00f62f8563317ac504b0b51ece853b89fabe692cf00000001113958989
2a169ce03f227e6@reply.github.com>
Date:  Sunday, April 5, 2015 at 16:10 PM
To:  TurboPack/SysTools <SysTools@noreply.github.com>
Cc:  Robert Grimes <rsgrimes@rcn.com>
Subject:  Re: [SysTools] Cannot compile StDict.pas  (#1)

**Comment by rsgrimes** [comment]
Hi Roman,

Don’t know if I mentioned it or not, but that did indeed fix the problem –
thanks!!!!!  (Sorry for the delay in updating you on this; I’ve been wicked
busy this month!)

Regards,
Bob

From:  Roman Kassebaum <notifications@github.com>
Reply-To:  TurboPack/SysTools
<reply+003b2b09baf00f62f8563317ac504b0b51ece853b89fabe692cf00000001113958989
2a169ce03f227e6@reply.github.com>
Date:  Sunday, April 5, 2015 at 16:10 PM
To:  TurboPack/SysTools <SysTools@noreply.github.com>
Cc:  Robert Grimes <rsgrimes@rcn.com>
Subject:  Re: [SysTools] Cannot compile StDict.pas  (#1)
