### ISSUE TITLE
Systools not working on XE10.2 - many string allocation issues. 

### ISSUE THREAD

**Issue by tom-abcd** [TurboPack/SysTools#11]
I am trying to use Systools with XE10.2 that was installed with Getit package manager. 
I have run across some string allocation issues.   ( I see the same issue in code I download from Github)

For example in Stregini.pas the strings are only allocated for length but should be Length + 1. 
Latter when they are freed it uses Length +1 and then errors out. 

constructor TStRegIni.Create(RootName : String; IsIniFile : Boolean);
var
  S   : string;
  OSI : TOSVERSIONINFO;
begin
{$IFDEF ThreadSafe}
  Windows.InitializeCriticalSection(riThreadSafe);
{$ENDIF}

  {check if a primary key or ini file is specified}
  if (Length(RootName) = 0) then
    RaiseRegIniError(stscNoFileKey);
  RootName := ANSIUpperCase(RootName);

  {get False string from resource}
  S := SysToolsStr(stscFalseString);
  riFalseString := StrAlloc(Length(S)); // GetMem(riFalseString,Length(S)+1);
  StrPCopy(riFalseString,S);

  {get True string from resource}
  S := SysToolsStr(stscTrueString);
  riTrueString := StrAlloc(Length(S)); // GetMem(riTrueString,Length(S)+1);
  StrPCopy(riTrueString,S);

Also found this in StOStr.pas where a pointer is copied but instead it should have copied over the data NOT the pointer.

procedure TStString.SetAsShortStr(const Value : string);
{- Copy short string into string object. }
begin
  FString := PChar(Value);
  ResetCursor;
end;

Unsure how this works for anyone but that seems unlikely so what am I doing wrong? 
I have also posted this on the embarcadero forum. 

Thanks 
Tom

**Comment by romankassebaum** [comment]
You should try https://github.com/TurboPack-Tokyo/SysTools for Tokyo.

**Comment by tom-abcd** [comment]
Still has the same problem.  I checked the .Create routine and the Destroy and it is the same as what I got with the Getit package manager.  ( I looked at the .pas files.   Plus what does the Getit pull from? )

**Comment by romankassebaum** [comment]
I tried to fix the issues which is very difficult with this old code. In Tokyo you could use TStringBuilder and TRegIniFile instead.

**Comment by tom-abcd** [comment]
Thanks for looking at this.   I will change as you recommend.   It would be helpful to put something in the readme that the these  classes do not work in the newer compilers so others do not run across this problem.  (or bug you :) )
