### ISSUE TITLE
Unable to install SysTools via GetIt in Delphi Rio 10.3.2

### ISSUE THREAD

**Issue by sigurdn** [TurboPack/SysTools#12]
The Install via get it fails with the following error .

Cannot load package 'SysToolDR260.' It contains unit 'StExpLog', wich is also contained in package 'SysToolsDR2410'
![systools](https://user-images.githubusercontent.com/15942701/62779140-dd7d7b00-baa1-11e9-991b-4f5a3cec2a4f.png)

**Comment by marcocantu** [comment]
I just installed it and all was good. YOu probably have an older version of the package already installed on your system...
