### ISSUE TITLE
C++ Builder files were not created with the default installer for 10.3.3 Rio

### ISSUE THREAD

**Issue by jaridmo** [TurboPack/SysTools#13]
Running the GetIt package installer for RadStudio the SysTools package was not compiled for C++ Builder (Missing all the hpp files).
Also the paths in the Tools - Options - C++ - Paths and Directories - System Include Path contained $(BDSCatalogRepository)\SysTools-4.3\source\hpp\Win32\Debug but when I opened and recompiled the packages the hpp files were placed in the source folder so the path needed to be changed to $(BDSCatalogRepository)\SysTools-4.3\source\

**Comment by romankassebaum** [comment]
You posted the same under LockBox.
