### ISSUE TITLE
bug/regression: StWMDataCopy: No longer works under win7 - WM_COPYDATA no longer gets through to WNDPROC

### ISSUE THREAD

**Issue by sbridger** [TurboPack/SysTools#2]
StFirst (sends a message to the first instance using WM_COPYDATA) no longer appears to work under win7
- It does sucessfully bring the first instance to the front
- It appears that the pascal code is running and making the windows call to send (SendMessage(TopWnd, WM_COPYDATA...) , but TForm1.StWMDataCopy1DataReceived is not called.

D7 version doesn't work either on Win7
DXE2 version does work on XP (with window normal or minimised)
So appears that this way of doing it, no longer works, or something extra needs to be done to enable it.

This suggest it is due to UIPI:
https://msdn.microsoft.com/en-us/library/ms649011(v=vs.85).aspx
and ChangeWindowsFilter is needed to fix it, (How to I get that fn in Delphi?)
http://msdn.microsoft.com/en-us/library/ms632675%28v=vs.85%29.aspx
But this guy I suggesting that this is not the way
http://www.nynaeve.net/?p=151

I have tried launching the sending copy of the application from and administrator console, and also using elevate to lauch it with higher permissions without success.

**Comment by sbridger** [comment]
Found ChangeWindowFilter example here:
http://stackoverflow.com/questions/360289/looking-for-an-alternative-to-windows-messages-used-in-inter-process-communicati
and implemented it as below, so I could try both variants of it. I tried these in Stfirst.Initialise and also in Form1.Create
Sadly no success....

```delphi
procedure ChangeMessageFilter(H:THandle=0);
var ChangeWindowMessageFilter: function (msg : Cardinal; dwFlag : Word) : BOOL; stdcall;
    ChangeWindowMessageFilterEx: function (H:THandle; msg : Cardinal; dwFlag : Word) : BOOL; stdcall;
begin
  //warning might fail on <=XP
  if (H=0) then begin
      @ChangeWindowMessageFilter := GetProcAddress(LoadLibrary('user32.dll'), 'ChangeWindowMessageFilter');
      ChangeWindowMessageFilter(WM_COPYDATA, 1);
    end else begin
      @ChangeWindowMessageFilterEx := GetProcAddress(LoadLibrary('user32.dll'), 'ChangeWindowMessageFilterEx');
      ChangeWindowMessageFilterEx(H,WM_COPYDATA, 1);
  end;
```

**Comment by sbridger** [comment]
Looks like it's not the UIPI as it seems you can check for UIPI fails in Sendmessage:

"When a message is blocked by UIPI the last error, retrieved with GetLastError, is set to 5 (access denied)."
https://msdn.microsoft.com/en-us/library/ms644950.aspx

So now I am checking this, and GetLastError returns 0, with or without ChangeWindowMessageFilter.

TStWMDataCopy.Create is being called, as is Hook. 
TStWMDataCopy.AppWndProc is being called all the time, but never with Msg = WM_COPYDATA

So not much left to try now. Perhaps registermessage?

**Comment by marcocantu** [comment]
Not sure, I worked on Windows 7 with WM_COPYDATA and don't remember any particular issue to get it to work...

**Comment by sbridger** [comment]
The problem seems to be in wmstdcpy or more likely in what delphi (doesn't) passes to the form windowproc.

I can make a working test example which hooks the application windowproc, with a raw procedure (ie not getting tmessage):
```
function NewWndProc(Handle: hWnd; Msg, wParam, lParam: Cardinal): LongInt; stdcall;

initialization
PrevWndProc := Pointer(SetWindowLong(Application.Handle, gwl_WndProc,
 Integer(@AppWndProcX)));
```

but ``` TStWMDataCopy.AppWndProc ``` does not get the copy messages (gets other routine messages)
It hooks the form windowproc (processed calls with tmessage) 

```
procedure TStWMDataCopy.AppWndProc(var Msg : TMessage);

//hooking....
PrevWndProc:= Pointer(
        SetWindowLong(TForm(Owner).Handle, GWL_WNDPROC, LongInt(NewWndProc)))
```

As I said before, this (dxe2) does get the messages under XP, but not under W7. 
Currently the working method only seems to work if the NewWndProc is in the form1 unit. Making it a class method of another unit seems to stop it working....

**Comment by sbridger** [comment]
So summary so far:
The issue is in StWMDataCopy not StFirst, which sends messages fine.
The problem happens in a simple demo as well as Realterm.
WM_COPYDATA works fine, it is the hooked APPWNDPROC in StWmDataCopy that is not getting these messages passed to it in Win7. For some reason it does get them in XP - so this is not related to any changes from D7->DXE2. (Old D7 version of program has same issue)
Hooking the Application windows proc directly does get these messages.
ChangeFilter does not affect this, and the sendmessageerror codes show that UIPI is not the problem,
Using RegisterMessage to make a custom message works fine, but only WM_COPYDATA actually passes any data through the kernel - other messages only pass the message number, the other (string) data gets lost. 
So I have simply directly hooked the application wndproc in form1. It works fine when hooked from FormCreate (not just from initialization)



```
var WProc:pointer;
//hooked from within FormCreate or initialization of Form1, both work
WProc := Pointer(SetWindowLong(Application.Handle, gwl_WndProc,Integer( @AppWndProcWMCopyData)));
```
```
// Hook window function and call same handler as used by StWMDataCopy
function AppWndProcWMCopyData(Handle: hWnd; Msg, wParam, lParam: Cardinal): LongInt; stdcall;
var
  CDS   : TCopyDataStruct; S:string;
begin
    if (Msg = WM_COPYDATA{fCustomMsg}) then begin
      CDS := PCopyDataStruct(Pointer(lParam))^;
      if (CDS.dwData = WMCOPYID) then Form1.StWMDataCopy1DataReceived(nil,CDS);
    Result:= 1;
  end else
      if Assigned(WProc) then
        Result:=CallWindowProc(WProc, Handle, Msg, wParam, lParam);
end;
```

**Comment by romankassebaum** [comment]
Some remarks:
1. I'm running a commercial application under Win7, Win8, Win8.1 and Win10 with WM_COPYDATA and everything is fine. That's why it is unlikely that there is a general issue in Delphi or in the VCL
2.  It is dangerous to send a PChar. I would convert the string to TBytes and send the bytes.
3.  I would need a test project.
4.  After so many years I close the case.
