### ISSUE TITLE
ValLongInt (and probably others) cannot work

### ISSUE THREAD

**Issue by GerhardSachs** [TurboPack/SysTools#3]
The ValLongInt procedure in the StBase unit cannot work.
It tries to read the string length from the first byte of the string using the absolute keyword.
But the string is a standard Delphi8 string.
No one would use this function in a new project, but I used Str2WordL in an old project.
In the StBase unit I used in Delphi XE7 the first parameter of ValLongInt was a ShortString and this is a must.
Someone changed this from ShortString to string in Delphi8.

**Comment by romankassebaum** [comment]
I fixed the calculation of the length.
