### ISSUE TITLE
stBits.pas stBits class is missing Bytes and AsString properties

### ISSUE THREAD

**Issue by sbridger** [TurboPack/SysTools#6]
My stBits.pas has the properties below, but this version doesn't. Where and when did they go?

    property Bytes[N : LongInt] : byte {gives direct access to bytes}
      {-Read or write Nth byte in set}
      read GetByte
      write SetByte;
    property AsString : AnsiString {gives access as longstring}
      read GetAsString
      write SetAsString;

**Comment by sbridger** [comment]
I can't see where or why these functions disappeared, as they were there in 4.03. Not sure if you want to revert to this, anyway here is my current version, 
- bug fix to GetAsString, 
- has removed functions restored
-all HUGExxxx removed
[StBits.zip](https://github.com/TurboPack/SysTools/files/622890/StBits.zip)

**Comment by romankassebaum** [comment]
The original version from sourceforge that I started with didn't have these props.

**Comment by romankassebaum** [comment]
Added your changesets.
