### ISSUE TITLE
Bug in StDateST.TimeStringToHMS function

### ISSUE THREAD

**Issue by edbuescher** [TurboPack/SysTools#8]
There is an infinite loop in the TimeStringToHMS function of StDateST.pas.

Line # 649 has been commented out and needs to be reinstated. The section of code starting at line 643 is:
...
643:      while (I <= Length(Picture)) and (Picture[I] = TimeOnly) do begin{!!.02}
644:  //      while (Picture[I] = TimeOnly) do begin
645:        //SZ Inc(Tmp[0]);
646:        //SZ Tmp[J] := St[I];
647:        Tmp := Tmp + St[I];
648://        Inc(J);
649://        Inc(I);  <----- This line needs to be reinstated
650:      end;
...
The while loop starting on line 643 will loop forever because "I" is not incremented

**Comment by romankassebaum** [comment]
Fixed.
