### ISSUE TITLE
Delphi XE5 doesn't know unit "System.Hash" in uses section of StDict.pas

### ISSUE THREAD

**Issue by code-kot** [TurboPack/SysTools#9]
https://github.com/TurboPack/SysTools/blob/master/source/StDict.pas#L194

Commit 749906248a13d24e2825c550b105c4934a230228 is the last compilable.

**Comment by romankassebaum** [comment]
TurboPack always is working with the latest version of RADStudio. For older versions I created in the past some branches, e.g. https://github.com/TurboPack-XE5/Orpheus.

But there are so few people working with them that these branches are not maintained.
